### ISSUE TITLE
The initial template does not load

### ISSUE THREAD

**Issue by JohnFulpWillard** [kiethstation-tgshiptest/tg-voidcrew#67]
## Reproduction:

1. Try to run the game

![image](https://user-images.githubusercontent.com/53777086/209424253-ad779d64-bcc6-4b27-b1d6-e6ec9b818ca3.png)
![image](https://user-images.githubusercontent.com/53777086/209424256-b0839e80-0c95-461c-91a2-c9c8811702b0.png)
![image](https://user-images.githubusercontent.com/53777086/209424315-9c6147df-bb45-45ba-8fe6-8577b02b8c77.png)

**Comment by ZephyrTFA** [comment]
the issue appears to be caused by checking job slots before the template datum converts slots to a job map

**Comment by ZephyrTFA** [comment]
which it should be doing in New unless i messed something up
